#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-openshift-s2i - DO180 Creating a Containerized Application with Source-to-Image
#
# SYNOPSIS
#     lab-openshift-s2i {start|finish}
#
#        start   - configures the environment at the start of a lab or exercise.
#        finish  - executes any administrative tasks after completion of a lab or exercise.
#
#     All functions only work on workstation
#
# DESCRIPTION
#     This script configures the initial state of the lab with lab and solution files.
#
# CHANGELOG
#   * Tue Dec 01 2020 Michael Phillips <miphilli@redhat.com>
#   - start function does not need to grab lab files as they are unnecessary and the exercise has been modified to not look at them.
#   * Thu Feb 14 2019 Eduardo Ramirez <eramirez@redhat.com>
#   - Updated to OCP 4.0
#   * Thu Jun 14 2018 Artur Glogowski
#   - updated to version 3.9
#   * Fri Apr 07 2017 Jim Rigsbee <jrigsbee@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'
this='openshift-s2i'
target='workstation'
title='Guided Excercise: Creating a Containerized Application with Source-to-Image'

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

project_name=php-helloworld
git_repo="http://services.lab.example.com/${project_name}"

# Additional functions for this grading script

function print_usage {
  local problem_name=$(basename $0 | sed -e 's/^lab-//')
  cat << EOF
This script controls the setup and grading of this lab.
Usage: lab ${problem_name} COMMAND
       lab ${problem_name} -h|--help

COMMAND is one of: ${valid_commands[@]}

EOF
}

function lab_start {
  print_header "Setting up ${target} for the ${title}"

  pad " · Installing the tree command"
  sudo yum install -y tree
  success_if_equal $? 0

  ocp4_verify_local_clone_exist

  ocp4_is_cluster_up

  pad " · Ensuring the '${RHT_OCP4_DEV_USER}-s2i' project does not exist"
  delete_project "${RHT_OCP4_DEV_USER}-s2i"
  success_if_equal $? 0
}

function lab_finish {
  print_header "Completing the ${title}"



  ocp4_login_as_developer
  pad " · Deleting the '${RHT_OCP4_DEV_USER}-s2i' project"
  if [ $? -eq 0 ]; then
    delete_project "${RHT_OCP4_DEV_USER}-s2i"
    success_if_equal $? 0
  else
    print_FAIL
  fi

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/labtool.shlib
source /usr/local/lib/labtool.do180.shlib

grading_main_program "$@"
