#!/usr/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-example - grading/setup script for DO180
#
# SYNOPSIS
#     lab-example {setup|grade|solve|reset}
#
#        setup   - configures
#        grade   - no grading done for this lab
#        solve   - download
#        reset   - remove
#
#     All functions only work on workstation
#
# DESCRIPTION
#     This script configures XXXX
#
# CHANGELOG
#   * Fri Mar 17 2017 Jim Rigsbee <jrigsbee@redhat.com>
#   - original code

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
this='example'
target='workstation'
title='Example Lab'

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(setup grade solve reset)

# Additional functions for this grading script

function print_usage {
  local problem_name=$(basename $0 | sed -e 's/^lab-//')
  cat << EOF
This script controls the setup and grading of this lab.
Usage: lab ${problem_name} COMMAND
       lab ${problem_name} -h|--help

COMMAND is one of: ${valid_commands[@]}

EOF
}

function lab_setup {

  grab_lab_files "true"
}

function lab_grade {

  echo
  echo "This is an exploratory lab - no grading functionality provided."
  echo

}

function lab_solve {

  lab_reset
  lab_setup

  echo -n '  Solving the lab for you (actually, nothing is being done) .......... '
    print_SUCCESS

  echo
}

function lab_reset {

  echo
  reset_lab
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/labtool.shlib
source /usr/local/lib/labtool.do180.shlib

grading_main_program "$@"
