#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-dockerfile-create - grading/setup script for DO276
#
# SYNOPSIS
#     lab-dockerfile-create{start|finish}
#
#        start   - configures the environment at the start of a lab or exercise.
#        finish  - executes any administrative tasks after completion of a lab or exercise.
#
#     All functions only work on workstation
#
# DESCRIPTION
#     This script is for the GE 'Building a basic apache container'
#
# CHANGELOG
#   * Fri Feb 8 2019 Jordi Sola <jordisola@redhat.com>
#   - Updated to podman and OCP4.0
#   * Fri Jun 8 2018 Artur Glogowski <aglogows@redhat.com>
#   - Updated to version 3.9
#
#   * Sun Apr 2 2017 Ravi Srinivasan <ravis@redhat.com>
#   - Updated for DO180
#   - Removed solve verb
#
#   * Sun Jan 10 2016 Zach Gutterman <zgutterm@redhat.com>
#   - original code from DO276

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
this='dockerfile-create'
target='workstation'
title='Guided Exercise: Building a basic Apache Container Image'

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

# Additional functions for this grading script

function print_usage {
  local problem_name=$(basename $0 | sed -e 's/^lab-//')
  cat << EOF
This script controls the setup and reset of this lab.
Usage: lab ${problem_name} COMMAND
       lab ${problem_name} -h|--help

COMMAND is one of: ${valid_commands[@]}

EOF
}

function lab_start {
  print_header "Setting up ${target} for the ${title}"

  #Remove once workstation is configured with
  # registry.lab.example.com as a registry.
  check_podman_registry_config

  grab_lab_files
}

function lab_finish {
  print_header "Completing the ${title}"

  pad " · Stopping lab-apache container that is running" && podman_stop_container "lab-apache"

  pad " · Removing lab-apache container that is in the cache" && podman_rm_container "lab-apache"

  pad " · Removing do180/apache custom container image" && podman_rm_image "localhost/do180/apache"

  pad " · Removing UBI7 container image" && remove_dependant_images "registry.access.redhat.com/ubi7/ubi"

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/labtool.shlib
source /usr/local/lib/labtool.do180.shlib

grading_main_program "$@"
