#!/usr/bin/bash
#
# Copyright 2017 Red Hat, Inc.
#
# NAME
#     lab-openshift-resources - grading/setup script for DO180
#
# SYNOPSIS
#     lab-openshift-resources {start|finish}
#
#        start   - configures the environment at the start
#                  of a lab or exercise.
#        finish  - executes any administrative tasks after
#                  completion of a lab or exercise.
#
#     All functions only work on workstation
#
# DESCRIPTION
#     This script is for the GE 'Deploying a Database Server on OpenShift'
#
# CHANGELOG
#   * Fri Feb 15 2019 Michael Jarrett <mjarrett@redhat.com>
#   - Updated to version 4.0
#   * Mon Jun 11 2018 Artur Glogowski <aglogows@redhat.com>
#   - Updated to version 3.9
#   * Fri Apr 7 2017 Ravi Srinivasan <ravis@redhat.com>
#   - Updated for DO180
#   - Removed solve verb
#
#   * Sun Jan 10 2016 Zach Gutterman <zgutterm@redhat.com>
#   - original code from DO276

PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

# Initialize and set some variables
run_as_root='true'
this='openshift-resources'
target='workstation'
title='Guided Exercise: Deploying a Database Server on OpenShift'
# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

# Additional functions for this grading script

function print_usage {
  local problem_name=$(basename $0 | sed -e 's/^lab-//')
  cat << EOF
This script controls the setup and reset of this lab.
Usage: lab ${problem_name} COMMAND
       lab ${problem_name} -h|--help

COMMAND is one of: ${valid_commands[@]}

EOF
}

function lab_start {
  print_header "Setting up ${target} for the ${title}"

  ocp4_is_cluster_up

  pad " · Ensuring the '${RHT_OCP4_DEV_USER}-mysql-openshift' project is absent"
  delete_project "${RHT_OCP4_DEV_USER}-mysql-openshift"
  success_if_equal $? 0
}



function lab_finish {
  print_header "Completing the ${title}"

  pad " · Deleting the '${RHT_OCP4_DEV_USER}-mysql-openshift' project"
  delete_project "${RHT_OCP4_DEV_USER}-mysql-openshift"
  success_if_equal $? 0

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/labtool.shlib
source /usr/local/lib/labtool.do180.shlib

grading_main_program "$@"
