#!/usr/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-multicontainer-openshift - start/finish script for DO180
#
# SYNOPSIS
#     lab-example {start|finish}
#
#        start  - configures the environment at the start of a lab or exercise.
#        finish - executes any administrative tasks after completion of a lab or exercise.
#
#     All functions only work on workstation
#
# DESCRIPTION
#     This script configures GE: Creating an Application with a Template
#
# CHANGELOG
#   * Tue Oct 15 2019 Jordi Sola <jordisola@redhat.com>
#   - Update to shared cluster and Quay.io
#   * Thu Wed 28 2019 Dan Kolepp <dkolepp@redhat.com>
#   - Conversion to start|finish verbs
#   - changed name of script to conform to file naming standards.
#   * Mon Apr 3 2017 Richard Allred <rallred@redhat.com>
#   - Initial code.

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
this="multicontainer-openshift"
title="Guided Exercise: Creating an Application with a Template"
target='workstation'

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

# Additional functions for this grading script

function print_usage {
  local problem_name=$(basename $0 | sed -e 's/^lab-//')
  cat << EOF
This script controls the start and completion of this lab.
Usage: lab ${problem_name} COMMAND
       lab ${problem_name} -h|--help

COMMAND is one of: ${valid_commands[@]}

EOF
}

function lab_start {
  print_header "Setting up ${target} for the ${title}"

  check_podman_registry_config

  print_line

  ocp4_is_cluster_up

  pad " · Ensure template project does not exist"
  delete_project ${RHT_OCP4_DEV_USER}-template
  success_if_equal $? 0

  pad " · Initializing local container image storage"
  podman_rm_image rhscl/mysql-57-rhel7

  grab_lab_files
  print_line
}

function lab_finish {
  print_header "Completing the ${title}"

  ocp4_login_as_developer
  pad " · Removing ${RHT_OCP4_DEV_USER}-template project"
  if [ $? -eq 0 ]; then
    delete_project ${RHT_OCP4_DEV_USER}-template
    success_if_equal $? 0
  else
    print_FAIL
  fi

  for image in rhscl/mysql-57-rhel7 \
               do180/mysql-57-rhel7 \
               quay.io/${RHT_OCP4_QUAY_USER}/do180-mysql-57-rhel7 \
               localhost/do180-nodejs \
               do180/todonodejs \
               quay.io/${RHT_OCP4_QUAY_USER}/do180-todonodejs \
               registry.access.redhat.com/ubi7/ubi:7.7 ; do

    pad " · Removing $image image" && podman_rm_image $image
  done
}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/labtool.shlib
source /usr/local/lib/labtool.do180.shlib

grading_main_program "$@"
