#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# NAME
#     lab-appendix-microservices - grading/setup script for DO180
#
# SYNOPSIS
#     lab-appendix-microservices {start|finish}
#
#        start   - configures the environment at the start of a lab or exercise.
#        finish  - executes any administrative tasks after completion of a lab or exercise.
#
#     All functions only work on workstation
#
# DESCRIPTION
#     This script configures GE: Breaking Up the To Do List Application
#
# CHANGELOG
#   * Fri Mar 08 2019 Eduardo Ramirez <eramirez@redhat.com>
#   - Upgrade to OCP 4.0
#   * Fri Jun 28 2018 Razique Mahroua <rmahroua@redhat.com>
#   - Upgrade to OCP 3.9
#   * Mon Apr 13 2017 Ricardo Jun <jtaniguc@redhat.com>
#   - Initial code.

PATH=/usr/bin:/bin:/usr/sbin:/sbin

# Initialize and set some variables
run_as_root='true'
this="appendix-microservices"
title="Guided Exercise: Breaking Up the To Do List Application"
target='workstation'

# This defines which subcommands are supported (solve, reset, etc.).
# Corresponding lab_COMMAND functions must be defined.
declare -a valid_commands=(start finish)

# Additional functions for this grading script

function print_usage {
  local problem_name=$(basename $0 | sed -e 's/^lab-//')
  cat << EOF
This script controls the setup and grading of this lab.
Usage: lab ${problem_name} COMMAND
       lab ${problem_name} -h|--help

COMMAND is one of: ${valid_commands[@]}

EOF
}

function lab_start {
  print_header "Setting up ${target} for the ${title}"

  check_podman_registry_config

  grab_lab_files
}

function lab_finish {
  print_header "Completing the ${title}"

  for container in mysql todoapi todo_frontend; do
    pad " · Stopping $container container" && podman_stop_container $container
    pad " · Removing $container container" && podman_rm_container $container
  done

  for image in localhost/do180/todonodejs \
               localhost/do180/todo_frontend \
               localhost/do180/httpd \
               registry.access.redhat.com/rhscl/mysql-57-rhel7 \
               registry.access.redhat.com/ubi7/ubi:7.7 \
               registry.access.redhat.com/rhscl/nodejs-8-rhel7 ; do
    pad " · Removing $image image" && podman_rm_image $image
  done

}

############### Don't EVER change anything below this line ###############

# Source library of functions
source /usr/local/lib/labtool.shlib
source /usr/local/lib/labtool.do180.shlib

grading_main_program "$@"
